# NumPy 한번에 제대로 배우기



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [1]:
import numpy as np
np.__version__

'1.21.5'



---



## 배열 생성

### 리스트로 배열 만들기


In [2]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2])
a1[0] = 4
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3
[4 2 3 4 5]


In [3]:
a2 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(a2)
print(a2.shape)
print(a2[0, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1


In [4]:
a3 = np.array([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
], [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
print(a3)
print(a3.shape)
print(a3[0, 0])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(2, 3, 3)
[1 2 3]


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [5]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

* `ones()`: 모든 요소를 1로 초기화

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [7]:
np.full(shape=(3, 3), fill_value=1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [9]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [10]:
temp = np.empty(10)
temp

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [11]:
print(a1)
np.zeros_like(a1)

[4 2 3 4 5]


array([0, 0, 0, 0, 0])

In [12]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
print(a3)
np.full_like(a3, 10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [14]:
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성
* https://appia.tistory.com/154

In [15]:
np.linspace(0,1, 5) # 0부터 1까지 5개의 균등한 간격

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [142]:
np.logspace(1,10,num = 10, base = 2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [148]:
np.logspace(1,5,num = 5, base = 10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [149]:
np.logspace(1,5,num = 5, base = 0.1)

array([1.e-01, 1.e-02, 1.e-03, 1.e-04, 1.e-05])

In [17]:
np.logspace(0.1, 1, 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

In [18]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

* 직접 추가
* `geospace()`: 기하수열이래.

In [19]:
print(np.geomspace(1, 1000, num=4))
print(np.geomspace(1, 1000, num=4, endpoint=False))
print(np.geomspace(1, 1000, num=3, endpoint=False))

[   1.   10.  100. 1000.]
[  1.           5.62341325  31.6227766  177.827941  ]
[  1.  10. 100.]


### 랜덤값으로 배열 생성


![image.png](attachment:image.png)

* `random.random()`: 랜덤한 수의 배열 생성

In [20]:
np.random.random((3, 3))

array([[0.80115595, 0.64520001, 0.74882482],
       [0.89236271, 0.40494683, 0.17980431],
       [0.8471634 , 0.16601537, 0.80783045]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [21]:
np.random.randint(0, 10, (3, 3)) # 시작, 끝, shape

array([[8, 1, 2],
       [6, 1, 1],
       [5, 4, 1]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [22]:
np.random.normal(0, 1, size=(3, 3)) # 평균, 표준편차, shape

array([[-0.5346    ,  0.50510743, -0.76926978],
       [-1.22561367,  0.19467102, -0.62314559],
       [-1.01639109,  0.34044545,  0.34680589]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [23]:
np.random.rand(3, 3)

array([[0.70517809, 0.16527769, 0.854371  ],
       [0.24440177, 0.19572357, 0.63288814],
       [0.72874352, 0.38876972, 0.63404955]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [24]:
np.random.randn(3, 3)

array([[ 0.39602531,  0.33224685,  1.25910994],
       [ 0.4515822 , -0.2968141 ,  0.59865982],
       [ 0.54503635, -0.09488815, -0.39558356]])

### 표준 데이터 타입

![image-2.png](attachment:image-2.png)

https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [25]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [27]:
np.full((3, 3), 1.0, dtype=np.float_) # 위의 링크에서 바뀐 넘파이 데이터타입 명명법을 확인

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성


![image.png](attachment:image.png)

In [28]:
data = np.array('2020-01-01', dtype=np.datetime64) # 스트링으로 들어가는게 아니라 날짜로 들어가게됨.
data

array('2020-01-01', dtype='datetime64[D]')

In [29]:
# 다음과 같은 연산을 할 수 있음.
data + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [30]:
datetime = np.datetime64('2020-06-01 12:00') #시간도 저장가능
datetime

numpy.datetime64('2020-06-01T12:00')

In [31]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns') #나노초 단위까지가면 ns붙이라는듯?
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')

In [32]:
datetime = np.datetime64('2020-06-01 12:00:12.34') #안붙이면 이렇게 되는구만
datetime

numpy.datetime64('2020-06-01T12:00:12.340')

In [33]:
datetime+ np.arange(12) # 마지막 단위에서 연산을 하는구만

array(['2020-06-01T12:00:12.340', '2020-06-01T12:00:12.341',
       '2020-06-01T12:00:12.342', '2020-06-01T12:00:12.343',
       '2020-06-01T12:00:12.344', '2020-06-01T12:00:12.345',
       '2020-06-01T12:00:12.346', '2020-06-01T12:00:12.347',
       '2020-06-01T12:00:12.348', '2020-06-01T12:00:12.349',
       '2020-06-01T12:00:12.350', '2020-06-01T12:00:12.351'],
      dtype='datetime64[ms]')



---



## 배열 조회

### 배열 속성 정보

In [34]:
def array_info(array):
    print(array)
    print('ndim:', array.ndim)
    print('shape:', array.shape)
    print('dtype:', array.dtype)
    print('size:', array.size)
    print('itemsize:', array.itemsize)
    print('nbytes', array.nbytes)
    print('strides:', array.strides) # 차원별 총 크기 같은 느낌인데?

In [35]:
array_info(a1) 
# nbtype = size * itemsize
# stride: 다음 차원으로 넘어가기 위해서는 하나의 아이탬 크기를 건너야함. 따라서 4.

[4 2 3 4 5]
ndim: 1
shape: (5,)
dtype: int64
size: 5
itemsize: 8
nbytes 40
strides: (8,)


In [36]:
array_info(a2)
# strides: 2차원에서 다음차원으로 넘어가려면 총 3개의 아이탬을 건너야함. 3 * 4 = 12
# +=> 1차원에서 다음 차원으로 넘어가려면 총 1개의 아이탬을 건너야함. itemsize= 4

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int64
size: 9
itemsize: 8
nbytes 72
strides: (24, 8)


In [37]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (2, 3, 3)
dtype: int64
size: 18
itemsize: 8
nbytes 144
strides: (72, 24, 8)


### 인덱싱(Indexing)

In [38]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 2 3 4 5]
4
3
5
4


In [39]:
print(a2)
print(a2[0, 0])
print(a2[0, 2])
print(a2[-1, 2])
print(a2[-2, -1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
9
6


In [40]:
# 귀찮.

### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [41]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 2 3 4 5]
[4 2]
[4 2 3 4 5]
[4]
[4 3 5]
[5 4 3 2 4]


In [42]:
print(a2)
print(a2[1])
print(a2[1, :])
print(a2[:2, :2])
print(a2[1:, ::-1])
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [43]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])

[4 2 3 4 5]
[2 3 5]


In [44]:
print(a2)
bi = np.random.randint(0, 2, (3, 3), dtype=bool)
print(bi)
print(a2[bi]) # 1차원으로 나오게 되네?

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True False  True]
 [False  True  True]
 [ True False False]]
[1 3 5 6 7]


### 팬시 인덱싱(Fancy Indedxing)

In [45]:
print(a1)
print([a1[0], a1[2]]) # 이건 리스트로 출력됨.
ind = [0, 2]
print(a1[ind]) # 중괄호 안에 리스트가 들어가면 되는건가?
ind = np.array([[0, 1],
             [2, 0]])
print(a1[ind]) # 1차원에도 2차원을 넣으면 2차원이 나옴.

[4 2 3 4 5]
[4, 3]
[4 3]
[[4 2]
 [3 4]]


In [46]:
print(a2)
row = np.array([0, 2])
col = np.array([1, 2])
print(a2[row, col]) # [[row1, row2, ....], [col1, col2....]] 이런식으로 사용하는듯
# 만약 3차원이면, [[axis1], [axis2], [axis3]] 이런식으로 쓰는듯?

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]


In [47]:
print(a2[row, :]) # 행은 [0, 2], 열은 전부다
print(a2[:, col])
print(a2[row,1])

[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [48]:
print(a1)
b1 = np.insert(a1, 0, 10) #a1행렬에서 axis=0의 0번째 위치에 10을 추가하라.
print(b1)
print(a1) #a1은 바뀌지 않음.

[4 2 3 4 5]
[10  4  2  3  4  5]
[4 2 3 4 5]


In [49]:
c1 = np.insert(a1, 2, 10) #a1행렬에서 axis=0의 2번째 위치에 10을 추가하라.
print(c1)

[ 4  2 10  3  4  5]


In [50]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0) #a1행렬에서 axis=0의 1번째 위치에 10을 추가하라==> 차원의 크기에 맞춰지는듯.
print(b2)
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [51]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9 #슬라이싱에 해당되는 모든 위치에 9를 집어넣음.
print(a1)

i = np.array([1, 3, 4])
a1[i] = 0 #fancy indexing
print(a1, 'Fancy indexing')

a1[i] += 4 #기존값에 4를 더하라는 듯.
print(a1, 'a1[i] += 4')

[4 2 3 4 5]
[1 2 3 4 5]
[9 2 3 4 5]
[9 0 3 0 0] Fancy indexing
[9 4 3 4 4] a1[i] += 4


In [52]:
print(a2)
a2[0, 0] = 1
a2[1, 1] = 2
a2[2, 2] = 3
a2[0] = 1 #0행의 모든 열의 데이터에 1을 집어넣음
print(a2, 'a2[0] = 1')
a2[1:, 2] = 9
print(a2, 'a2[1:, 2] = 9')

#fancy indexingnumpy.logspace(1,10,num = 10, base = 2)
row = np.array([0, 1])
col = np.array([1, 2])
c2[row, col] = 0
print(a2, '<-- fancy Indexing')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [4 2 6]
 [7 8 3]] a2[0] = 1
[[1 1 1]
 [4 2 9]
 [7 8 9]] a2[1:, 2] = 9
[[1 1 1]
 [4 2 9]
 [7 8 9]] <-- fancy Indexing


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [53]:
print(a1)
b1 = np.delete(a1, 1) #1번 위치에 있는 인스턴스 삭제
print(b1)
print(a1) #원본 배열은 변경이 없음

[9 4 3 4 4]
[9 3 4 4]
[9 4 3 4 4]


In [54]:
print(a2)
b2 = np.delete(a2, 1, axis=0) #1번쨰 행 삭제
print(b2)
c2 = np.delete(a2, 1, axis=1)
print(c2)

[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 1 1]
 [7 8 9]]
[[1 1]
 [4 9]
 [7 9]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님


* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [55]:
print(a2)
a2_sub = a2[:2, :2]
print(a2_sub, '<--a2_sub')

a2_sub[:, 1] = 0
print(a2_sub, '<--a2_sub=[:, 1] = 0')
print(a2, '<--a2')
#원본이 변경되는 것을 볼 수 있음. 슬라이싱은 원본에서 그냥 참조해서 보여주기만 하는 듯.

[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 1]
 [4 2]] <--a2_sub
[[1 0]
 [4 0]] <--a2_sub=[:, 1] = 0
[[1 0 1]
 [4 0 9]
 [7 8 9]] <--a2


In [56]:
print(a2)
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy, '<--a2_sub_copy')
a2_sub_copy[:, 1] = 1
print(a2_sub_copy, '<--a2_sub_copy[:, 1] = 1')
print(a2, '<--a2 바뀌지 않음')

[[1 0 1]
 [4 0 9]
 [7 8 9]]
[[1 0]
 [4 0]] <--a2_sub_copy
[[1 1]
 [4 1]] <--a2_sub_copy[:, 1] = 1
[[1 0 1]
 [4 0 9]
 [7 8 9]] <--a2 바뀌지 않음




---



## 배열 변환

### 배열 전치 및 축 변경

In [57]:
print(a2)
print(a2.T, a2.T.shape)

[[1 0 1]
 [4 0 9]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 9 9]] (3, 3)


In [58]:
print(a3, a3.shape)
print(a3.T, a3.T.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]] (2, 3, 3)
[[[1 1]
  [4 4]
  [7 7]]

 [[2 2]
  [5 5]
  [8 8]]

 [[3 3]
  [6 6]
  [9 9]]] (3, 3, 2)


In [59]:
print(a3)
print(a3.swapaxes(1, 0), a3.swapaxes(1, 0).shape)
print(a3.swapaxes(1, 2), a3.swapaxes(1, 0).shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]]] (3, 2, 3)
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]] (3, 2, 3)


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [60]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3, 3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가

In [61]:
print(n1)
print(n1[np.newaxis, :5], n1[np.newaxis, :5].shape) #기존 차원을 행으로 만들고, 2차원으로 생성.
print(n1[:5, np.newaxis], n1[:5, np.newaxis].shape) #기존 차원을 열로 만들고 2차원으로 생성.

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]] (1, 5)
[[1]
 [2]
 [3]
 [4]
 [5]] (5, 1)


### 배열 크기 변경

* 배열 모양만 변경

In [62]:
# resize메서드인데, 잘 안쓸거 같은데?

In [63]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
n2.resize((5, 2))
print(n2)

[[9 4 3 5 5]
 [0 6 6 2 6]]
[[9 4]
 [3 5]
 [5 0]
 [6 6]
 [2 6]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [64]:
n2.resize((5, 5))
print(n2)

[[9 4 3 5 5]
 [0 6 6 2 6]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [65]:
n2.resize((3, 3))
print(n2)

[[9 4 3]
 [5 5 0]
 [6 6 2]]


### (np.append, np.stack) 배열 추가

* `append()`: 배열의 끝에 값 추가

In [66]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.arange(10, 19).reshape(3, 3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [67]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [68]:
c2 = np.append(a2, b2, axis=0) #0번째 차원(행)이 변하는 방향으로 합쳐짐(0번째 차원이 가장 고차원으로 생각하는게 나은가?).
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [69]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### (np.concatenate) 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [70]:
a1 = np.array([1, 3, 5])
b1 = np.array([2, 4, 6])
np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [71]:
c1 = np.array([7, 8, 9])
np.concatenate([a1, b1, c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [72]:
a2 = np.array([[1,2,3],
              [4, 5, 6]])
np.concatenate([a2, a2]) #기본 axis=0

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [73]:
a2 = np.array([[1,2,3],
              [4, 5, 6]])
np.concatenate([a2, a2], axis=1) #현재 2차원구조체이기 때문에 axis=2 에서는 안붙음. 새로운 차원을 추가해야 가능함.

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [74]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [75]:
np.hstack([a2, a2]), np.hstack([a2, a2]).shape

(array([[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6]]), (2, 6))

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [76]:
np.dstack([a2, a2]), np.dstack([a2, a2]).shape #이건 concat과 달리축이 없어도 붙는구나

(array([[[1, 1],
         [2, 2],
         [3, 3]],
 
        [[4, 4],
         [5, 5],
         [6, 6]]]), (2, 3, 2))

* `stack()`: 새로운 차원으로 연결

In [77]:
np.stack([a2, a2]), np.stack([a2, a2]).shape

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]), (2, 2, 3))

### (np.split) 배열 분할

* `split()`: 배열 분할

In [78]:
a1 = np.arange(0, 10)
print(a1)
b1, c1 = np.split(a1, [5]) #인덱스5 앞지점에서 자른다.
print(b1, c1)
print('=============')
b1, c1, d1, e1, f1 = np.split(a1, [2, 4, 6, 8])
print(b1, c1, d1, e1, f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [79]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.vsplit(a2, [2]) #3번째행(행2) 앞에서 짜른다.
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [80]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.hsplit(a2, [2]) #3번째행(행2) 앞에서 짜른다.
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [81]:
a3 = np.arange(1, 28).reshape(3, 3, 3)
print(a2)
b3, c3 = np.dsplit(a3, [2]) #3번째행(행2) 앞에서 짜른다.
print(b3)
print(c3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

In [82]:
# [1,2,3] +3 <-- 리스트에서는 이게 안되지.

### 브로드캐스팅(Broadcasting)

![image.png](attachment:image.png)

In [83]:
a1 = np.array([1, 2, 3])
print(a1)
print(a1 + 5)

[1 2 3]
[6 7 8]


In [84]:
# 귀찮으니 넘어간다.

### 산술 연산(Arithmetic Operators)

![image-2.png](attachment:image-2.png)

In [85]:
# 귀찮음.

In [86]:
# 다차원 + 스칼라
# 다차원 + 다차원 (t산술연산끼리는 같은 차원 & 같은 shape이여야함.)

#### (np.abs) 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [87]:
a1 = np.random.randint(-10, 10, size=5)
print(a1)
print(np.abs(a1))

[-9 -7  5  2  8]
[9 7 5 2 8]


#### (np.square, np.sqrt) 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

In [88]:
print(a1)
print(np.sqrt(a1)) #square root라는데

[-9 -7  5  2  8]
[       nan        nan 2.23606798 1.41421356 2.82842712]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


#### (np.exp, exp2, power, log, log2, log10) 지수와 로그 함수 (Exponential and Log Function)

In [89]:
a1 = np.random.randint(1, 10, size=5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1, 2))

[1 6 4 9 4]
[2.71828183e+00 4.03428793e+02 5.45981500e+01 8.10308393e+03
 5.45981500e+01]
[  2.  64.  16. 512.  16.]
[ 1 36 16 81 16]


In [90]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[1 6 4 9 4]
[0.         1.79175947 1.38629436 2.19722458 1.38629436]
[0.        2.5849625 2.        3.169925  2.       ]
[0.         0.77815125 0.60205999 0.95424251 0.60205999]


#### 삼각 함수(Trigonometrical Function)
https://rfriend.tistory.com/296

![image.png](attachment:image.png)

In [91]:
t = np.linspace(0, np.pi, 3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [92]:
x = [-1, 0, 1]
print(x)
print(np.arcsin(x))
print(np.arctan(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[-0.78539816  0.          0.78539816]
[-0.78539816  0.          0.78539816]


### 집계 함수(Aggregate Functions)

![image.png](attachment:image.png)
![image-3.png](attachment:image-3.png)

- nan이 붙은건 안전모드: 값이없으면 에러를 배출하는게 아닌 null값을 넣어줌

#### sum(): 합 계산

In [93]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis=0), np.sum(a2, axis=0))
print(a2.sum(axis=1), np.sum(a2, axis=1))

[[2 7 6]
 [6 5 3]
 [4 6 9]]
48 48
[12 18 18] [12 18 18]
[15 14 19] [15 14 19]


#### cumsum(): 누적합 계산

In [94]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(a2.cumsum())
print(np.cumsum(a2, axis=0))
print(a2.cumsum(axis=1))

[[4 9 8]
 [4 6 5]
 [8 1 5]]
[ 4 13 21 25 31 36 44 45 50]
[[ 4  9  8]
 [ 8 15 13]
 [16 16 18]]
[[ 4 13 21]
 [ 4 10 15]
 [ 8  9 14]]


#### diff(): 차분 계산-뒤에값을 앞의 값으로 뺀다 = 앞에 값에서 뒤에 값이 되기 위함.

In [95]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
# print(a2.diff()) <-- 메서드는 존재하지 않는듯.
print(np.diff(a2))
print(np.diff(a2, axis=0))
print(np.diff(a2, axis=1))
# print(a2.diff(axis=1))

[[4 9 3]
 [1 8 1]
 [1 9 6]]
[[ 5 -6]
 [ 7 -7]
 [ 8 -3]]
[[-3 -1 -2]
 [ 0  1  5]]
[[ 5 -6]
 [ 7 -7]
 [ 8 -3]]


#### prod(): element들에 대한 곱 계산

In [96]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(a2.prod())
print(np.prod(a2, axis=0))
print(a2.prod(axis=1))

[[1 3 9]
 [4 5 2]
 [2 8 9]]
155520
[  8 120 162]
[ 27  40 144]


#### cumprod(): 누적곱 계산

In [97]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(a2.cumprod())
print(np.cumprod(a2, axis=0))
print(a2.cumprod(axis=1))

[[9 5 3]
 [6 7 5]
 [3 4 8]]
[      9      45     135     810    5670   28350   85050  340200 2721600]
[[  9   5   3]
 [ 54  35  15]
 [162 140 120]]
[[  9  45 135]
 [  6  42 210]
 [  3  12  96]]


#### dot()/matmul(): 점곱/행렬곱 계산

* https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=cjh226&logNo=221356884894
* dot과 matmul의 차이
* 2차원까지는 동일한 연산을 수행하나, 3차원부터 용법이 전혀 다르다.


In [98]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2, b2))
print(np.matmul(a2, b2))

[[9 5 3]
 [6 7 5]
 [3 4 8]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[17 17 17]
 [18 18 18]
 [15 15 15]]
[[17 17 17]
 [18 18 18]
 [15 15 15]]


#### tensordot(): 텐서곱 계산

In [99]:
print(a2)
print(b2)
print(np.tensordot(a2, b2))
print(np.tensordot(a2, b2, axes=0)) #axis가 아닌것을 확인할 수 있음.
print(np.tensordot(a2, b2, axes=1))

[[9 5 3]
 [6 7 5]
 [3 4 8]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
50
[[[[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[6 6 6]
   [6 6 6]
   [6 6 6]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]]


 [[[3 3 3]
   [3 3 3]
   [3 3 3]]

  [[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]]]
[[17 17 17]
 [18 18 18]
 [15 15 15]]


#### cross(): 벡터곱

In [100]:
x = [1,2,3]
y = [4,5,6]
print(np.cross(x, y)) #2*6 - 3*5, 3*5 - 1*6, 1*5- 2*8

[-3  6 -3]


#### inner()/outer(): 내적/외적

np.dot()과 np.inner()는 서로 다릅니다. inner의 (i,j)원소는 앞 행렬의 i번째 행과 뒤 행렬의 j번째 행의 내적으로 계산됩니다. dot의 경우는 앞 행렬의 i번째 행과 뒤 행렬의 j번째 열의 내적입니다.

In [101]:
print(a2)
print(b2)
print(np.inner(a2, b2))
print(np.outer(a2, b2))

[[9 5 3]
 [6 7 5]
 [3 4 8]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[17 17 17]
 [18 18 18]
 [15 15 15]]
[[9 9 9 9 9 9 9 9 9]
 [5 5 5 5 5 5 5 5 5]
 [3 3 3 3 3 3 3 3 3]
 [6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7]
 [5 5 5 5 5 5 5 5 5]
 [3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4]
 [8 8 8 8 8 8 8 8 8]]


#### mean(): 평균 계산

In [102]:
print(a2)
print(a2.mean())
print(np.mean(a2, axis=0))
print(a2.mean(axis=1))

[[9 5 3]
 [6 7 5]
 [3 4 8]]
5.555555555555555
[6.         5.33333333 5.33333333]
[5.66666667 6.         5.        ]


#### std(): 표준 편차 계산

In [103]:
print(a2)
print(a2.std())
print(np.std(a2, axis=0))
print(a2.std(axis=1))

[[9 5 3]
 [6 7 5]
 [3 4 8]]
2.006163342807532
[2.44948974 1.24721913 2.05480467]
[2.49443826 0.81649658 2.1602469 ]


#### var(): 분산 계산

In [104]:
print(a2)
print(a2.var())
print(np.var(a2, axis=0))
print(a2.var(axis=1))

[[9 5 3]
 [6 7 5]
 [3 4 8]]
4.0246913580246915
[6.         1.55555556 4.22222222]
[6.22222222 0.66666667 4.66666667]


#### min(): 최소값

In [105]:
print(a2)
print(a2.min())
print(np.min(a2, axis=0))
print(a2.min(axis=1))

[[9 5 3]
 [6 7 5]
 [3 4 8]]
3
[3 4 3]
[3 5 3]


#### max(): 최대값

In [106]:
print(a2)
print(a2.max())
print(np.max(a2, axis=0))
print(a2.max(axis=1))

[[9 5 3]
 [6 7 5]
 [3 4 8]]
9
[9 7 8]
[9 7 8]


#### argmin(): 최소값 인덱스

In [107]:
print(a2)
print(a2.argmin())
print(np.argmin(a2, axis=0))
print(a2.argmin(axis=1))

[[9 5 3]
 [6 7 5]
 [3 4 8]]
2
[2 2 0]
[2 2 0]


#### argmax(): 최대값 인덱스

In [108]:
print(a2)
print(a2.argmax())
print(np.argmax(a2, axis=0))
print(a2.argmax(axis=1))

[[9 5 3]
 [6 7 5]
 [3 4 8]]
0
[0 1 2]
[0 1 2]


#### median(): 중앙값

In [109]:
print(a2)
# print(a2.median()) #중앙값은 없음
print(np.median(a2))
print(np.median(a2, axis=0))
# print(a2.median(axis=1))

[[9 5 3]
 [6 7 5]
 [3 4 8]]
5.0
[6. 5. 5.]


#### percentile(): 백분위 수



![image.png](attachment:image.png)

In [110]:
a1 = np.array([0, 1, 2, 3])
print(a1)
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='linear'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='higher'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='lower'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='nearest'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


#### any() : 하나라도 맞으면 True

In [111]:
n2 = np.array([[False, False, False],
              [False, True, True],
              [False, True, True]])
print(a2)
print(np.any(n2))
print(np.any(n2, axis=0))
print(np.any(n2, axis=1))

[[9 5 3]
 [6 7 5]
 [3 4 8]]
True
[False  True  True]
[False  True  True]


#### all() : 전부다 맞으면 True

In [112]:
n2 = np.array([[False, False, False],
              [False, True, True],
              [False, True, True]])
print(n2)
print(np.all(n2))
print(np.all(n2, axis=0))
print(np.all(n2, axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
False
[False False False]
[False False False]


In [113]:
n2 = np.array([[2, 3, 4],
              [1, 2, 3],
              [33, 4, 3]]) # 0 = False, 나머지는 true
print(n2)
print(np.all(n2))
print(np.all(n2, axis=0))
print(np.all(n2, axis=1))

[[ 2  3  4]
 [ 1  2  3]
 [33  4  3]]
True
[ True  True  True]
[ True  True  True]


### 비교 연산(Comparison Operators)


![image.png](attachment:image.png)

In [114]:
a1 = np.arange(1, 10)
print(a1)
print(a1 == 5) #해당되는 위치에 나옴

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]


In [115]:
# 나머지는 귀찮음.

In [116]:
# 이런식으로도 사용할 수 있음.
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(np.count_nonzero(a2 > 5))
print(np.sum(a2 > 5))
print(np.sum(a2 > 5, axis=0))
print(np.sum(a2 > 5, axis=1))
print(np.any (a2 > 5))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
4
4
[1 1 2]
[0 1 3]
True


![image.png](attachment:image.png)

In [117]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
b1 = np.array([1, 2, 3, 3, 4])
print(b1)
print(np.isclose(a1, b1))

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [118]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1)) #무한대가 아닌것만

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


#### 불리언 연산자(Boolean Operators)


![image.png](attachment:image.png)

![image.png](attachment:image.png)# 귀찮으니 생략


#### isnan(): null값 확인

In [ ]:
np.isnan(n)

### (np.sort, argsort)배열 정렬

In [119]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.sort(a1), '<-np.sort(a1)')
print(a1)
print(np.argsort(a1), '<-np.argsort(a1)')#인덱스 결과를 보여줌
print(a1) #원본 배열은 그대로임
print(a1.sort(), '<-a1.sort() 실행') #이건 원본 배열을 바꾸는 메서드임
print(a1)

[9 8 1 9 4 5 9 4 4 8]
[1 4 4 4 5 8 8 9 9 9] <-np.sort(a1)
[9 8 1 9 4 5 9 4 4 8]
[2 4 7 8 5 1 9 0 3 6] <-np.argsort(a1)
[9 8 1 9 4 5 9 4 4 8]
None <-a1.sort() 실행
[1 4 4 4 5 8 8 9 9 9]


In [120]:
a2= np.random.randint(1, 10, size=(3, 3))
print(a2)
print(np.sort(a2, axis=0))
print(np.sort(a2, axis=1))

[[7 5 3]
 [8 1 9]
 [3 7 3]]
[[3 1 3]
 [7 5 3]
 [8 7 9]]
[[3 5 7]
 [1 8 9]
 [3 3 7]]


#### (np.partition)부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

In [121]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.partition(a1, 3)) #가장 작은값 3개를 앞으로 

[8 5 8 2 4 9 4 2 3 6]
[2 2 3 4 4 5 6 9 8 8]


In [122]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
print(np.partition(a2, 3))
print(np.partition(a2, 3, axis=0))
print(np.partition(a2, 3, axis=1))

[[1 2 9 3 4]
 [6 2 6 6 1]
 [7 5 8 9 1]
 [9 9 1 9 7]
 [9 5 1 6 2]]
[[3 1 2 4 9]
 [2 1 6 6 6]
 [5 1 7 8 9]
 [1 7 9 9 9]
 [1 2 5 6 9]]
[[6 2 1 3 1]
 [1 2 1 6 1]
 [7 5 6 6 2]
 [9 5 8 9 4]
 [9 9 9 9 7]]
[[3 1 2 4 9]
 [2 1 6 6 6]
 [5 1 7 8 9]
 [1 7 9 9 9]
 [1 2 5 6 9]]


## 배열 입출력


![image.png](attachment:image.png)

In [123]:
a2 - np.random.randint(1, 10, size=(5, 5))
print(a2)
np.save('filename.npy', a2)

[[1 2 9 3 4]
 [6 2 6 6 1]
 [7 5 8 9 1]
 [9 9 1 9 7]
 [9 5 1 6 2]]


In [124]:
!dir
#이건 윈도우
#!ls #이건 리눅스

ab.npz	a.csv  b.csv  filename.npy  sample_data


In [125]:
b2 = np.random.randint(1, 10, size=(5, 5))
print(b2)
np.savez("ab.npz", a2, b2)
!dir

[[4 5 3 3 3]
 [5 9 8 2 5]
 [7 9 2 9 1]
 [2 2 7 2 4]
 [9 3 2 2 5]]
ab.npz	a.csv  b.csv  filename.npy  sample_data


In [126]:
npy = np.load('filename.npy')
print(npy)

[[1 2 9 3 4]
 [6 2 6 6 1]
 [7 5 8 9 1]
 [9 9 1 9 7]
 [9 5 1 6 2]]


In [127]:
npz = np.load('ab.npz')
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[1 2 9 3 4]
 [6 2 6 6 1]
 [7 5 8 9 1]
 [9 9 1 9 7]
 [9 5 1 6 2]]
[[4 5 3 3 3]
 [5 9 8 2 5]
 [7 9 2 9 1]
 [2 2 7 2 4]
 [9 3 2 2 5]]


In [128]:
print(a2)
np.savetxt('a.csv', a2, delimiter=',')

[[1 2 9 3 4]
 [6 2 6 6 1]
 [7 5 8 9 1]
 [9 9 1 9 7]
 [9 5 1 6 2]]


In [129]:
!dir

ab.npz	a.csv  b.csv  filename.npy  sample_data


In [130]:
# !cat a.csv
# 리눅스 명령어임

In [131]:
csv = np.loadtxt('a.csv', delimiter=',')
print(csv)

[[1. 2. 9. 3. 4.]
 [6. 2. 6. 6. 1.]
 [7. 5. 8. 9. 1.]
 [9. 9. 1. 9. 7.]
 [9. 5. 1. 6. 2.]]


In [132]:
print(b2)
np.savetxt('b.csv', b2, delimiter=',', fmt='%.2e', header='c1, c2, c3,c4, c5') #소수점 2번째자리까지, 헤더

[[4 5 3 3 3]
 [5 9 8 2 5]
 [7 9 2 9 1]
 [2 2 7 2 4]
 [9 3 2 2 5]]


In [133]:
csv = np.loadtxt('b.csv', delimiter=',')
print(csv)

[[4. 5. 3. 3. 3.]
 [5. 9. 8. 2. 5.]
 [7. 9. 2. 9. 1.]
 [2. 2. 7. 2. 4.]
 [9. 3. 2. 2. 5.]]


## 데이터 처리 관련 추가내용

### (np.bincount) 빈도수 구하기

- 1차원 배열과 양의 정수형인 객체에 적용함.
- 객체의 원소중 0부터 최대값 범위의 정수 값을 오름차순으로 정리한 뒤, 각 원소에 대한 빈도수를 반환함
- https://datastory1.blogspot.com/2017/12/blog-post.html
- https://numpy.org/doc/stable/reference/generated/numpy.bincount.html

In [134]:
x=np.random.randint(1, 10, 50)
x

array([5, 9, 8, 7, 1, 2, 6, 3, 7, 6, 3, 1, 3, 2, 3, 8, 1, 9, 3, 8, 3, 7,
       2, 6, 5, 9, 8, 2, 2, 9, 5, 1, 4, 9, 4, 8, 4, 2, 6, 9, 7, 4, 7, 4,
       6, 3, 5, 2, 5, 8])

In [135]:
 min(x), max(x)

(1, 9)

In [136]:
np.bincount(x)

array([0, 4, 7, 7, 5, 5, 5, 5, 6, 6])



---



### (np.where) 넘파이 if 문 느낌.



In [137]:
# https://ddolcat.tistory.com/654